### ISSUE TITLE
Collection of Swagger specs to be used for Examples & Tests

### ISSUE THREAD

**Issue by IvanGoncharov** [khangiskhan/swagger-commander#5]
@khangiskhan I working on [collection](https://github.com/APIs-guru/api-models) of swagger specs. At the moment it has 237 APIs including Instagram, Spotify, Azure APIs, Google APIs and much more.

You can use it to provide example other than Petstore.
Also, you can access the collection through [REST API](https://apis.guru/api-doc/) so it possible to run automatic tests on the entire collection.

**Comment by khangiskhan** [comment]
Hi Ivan,

This is great, I'll work on integrating these into examples and tests.

**Comment by IvanGoncharov** [comment]
@khangiskhan BTW we have Gitter chat https://gitter.im/APIs-guru/api-models
If you need help or have a question feel free to contact me in Gitter, Skype(ivangon4arov) or Hangouts(ivan.goncharov.ua@gmail.com).
