### ISSUE TITLE
take JSON data from stdin or an @file?

### ISSUE THREAD

**Issue by catenate** [khangiskhan/swagger-commander#6]
I find it convenient to compose JSON as a separate file, and upload it to servers using the "--data @filename" option of curl.  Swagger-commander is easier to use than curl (it's certainly a less-complex command), but it looks like if I want to upload data, I have to provide it on the command line.

As far as I know, stdin is unused by swagger-commander, so instead of a block of JSON as a parameter, could there maybe be something like a - parameter (like cat(1)), which reads from stdin and uses it in place of the parameter -?

For example, in addition to:

swagger-commander pet addPet '{"name":"Weasley", "status":"sold"}'

I suggest, where the file Weasley-sold contains this JSON snippet, that it also accepts either

cat Weasley-sold | swagger-commander pet addPet -

or perhaps:

swagger-commander pet addPet @Weasley-sold

which uses the mentioned curl parameter notation.

Thank you for your time and consideration!

**Comment by khangiskhan** [comment]
Hey there.  This is a great idea, I'll play around with it a bit and see how it works out.  Of course, feel free to submit a PR if you can get something working. 

Thanks!

**Comment by khangiskhan** [comment]
@catenate Added support for curl-like @ file arguments.

Published and pushed to npm, version 0.6.7.

Let me know if this fits your needs!

-khangiskhan

**Comment by khangiskhan** [comment]
Fixed/implemented.

https://github.com/khangiskhan/swagger-commander/commit/09b17687357b37f5698af3001c3a2f254f0fa9a4
